### ISSUE TITLE
Granular control over information we get from model summary

### ISSUE THREAD

**Issue by sidwa** [sksq96/pytorch-summary#121]
The summary function seems to print the model summary. However I'm trying to extract only total size of model from the summary for multiple models. 
It would be great if we had access to the summary_string() function so that we could extract the info we want using re or the summary() function returned all the parameter it calculated in a dictionary.

EDIT: summary_string() is available but through this github repo. PyPi version has not been updated.

**Comment by TylerYep** [comment]
Fixed in my fork -  see #124
