### ISSUE TITLE
Parameters being calculated using forward pass

### ISSUE THREAD

**Issue by praneet195** [sksq96/pytorch-summary#127]
Hi,

So, I found this issue and I think it's slightly misleading. Torchsummary uses a forward pass to determine layer structure and calculate parameters. Hence, if there is a for loop in the forward pass there is an issue.
```
def __init__: 
                self.conv1 = nn.Conv2d(x,y,z)
def forward(self,x):
                for i in range(5):
                    x = self.conv1(x)
```
As seen from the above snippet, I'm passing through the same layer again and again.
Torchsummary in this case will say that there are 5 layers (report 5 times the parameters) instead of 1 layer being cycled again and again. 
Although this is wrong code and goes against the concept of Neural Nets being Direct Acyclic Graphs, I hope there is some sort of check  in place to ensure the correct structure of the network created and parameters counted.
5 layers should only be reported when I use this:
```
def __init__:
        self.conv1 = nn.ModuleList([nn.Conv2d(x,y,z) for _ in range(5)])
def forward(self,x):
        for i in self.conv1:
               x = self.conv1(x)
```
Here, I've created 5 new layers and torchsummary prints the correct result but it should not print this type of result in the previous case

**Comment by TylerYep** [comment]
This is fixed in my fork - see #124
