### ISSUE TITLE
'PackedSequence' problem when there's RNN module in the model

### ISSUE THREAD

**Issue by leitro** [sksq96/pytorch-summary#128]
Hi! I'm using pytorch 1.4 and there occurs an error that:
```
AttributeError: 'PackedSequence' object has no attribute 'size'
```
I think it is because of the RNN module in my model, do you guys know which part I need to modify in the source code to make it work? Cheers!

**Comment by TylerYep** [comment]
Try #124 and see if that works? Otherwise you can submit an issue on my fork and I can look at it more closely.

**Comment by leitro** [comment]
> Try #124 and see if that works? Otherwise you can submit an issue on my fork and I can look at it more closely.

Cheers man!! It works:-)  I'll close this issue and for sure recommend this [repo](https://github.com/TylerYep/torch-summary) for guys who are also working on RNN stuff.
