### ISSUE TITLE
Summary assumes Cuda

### ISSUE THREAD

**Issue by system123** [sksq96/pytorch-summary#14]
Summary assumes that the model is on the GPU if cuda is available, this is not always the case and should rather be left up to the user to specify if it should use the GPU or CPU.

**Comment by soravux** [comment]
I get around this issue by having `CUDA_VISIBLE_DEVICES=''` in the environment variables.
In bash-like shells, you can do so by prepending it to the python call, as such (supposing $ is the shell prompt):
`$ CUDA_VISIBLE_DEVICES='' python <themodule.py>`

Sure, it's just a workaround for the time being...

**Comment by system123** [comment]
Thanks for the work around. Perhaps I'll submit a PR for the fix if I get
sometime before you.

**Comment by nikky4D** [comment]
In the main file, you can remove the need for cuda by commenting out the lines:

        if torch.cuda.is_available():
            dtype = torch.cuda.FloatTensor
        else:
            dtype = torch.FloatTensor

As long as the model is on the cpu, everything should work. 

Another workaround is to have the user decide what the dtype should be. So make it an input into the summary() method

**Comment by system123** [comment]
I have already fixed and made a PR for this issue. Thanks for the info though.
