### ISSUE TITLE
Add support for print_fn

### ISSUE THREAD

**Issue by nicoulaj** [sksq96/pytorch-summary#26]
Keras summary has a `print_fn` argument, so you can use it with logging, or writing into a file:
```
model.summary(print_fn=logging.info)
```
It would be nice to do the same instead of using `print`.

**Comment by Naireen** [comment]
we've recently extended it with #100 such that you can call `model.summary_string` instead of `model.summary` if you with the string to be returned instead of printed, and then you can write it to a file if you want, so I'll be closing this.
