### ISSUE TITLE
Syntax error during importing

### ISSUE THREAD

**Issue by IvanEz** [sksq96/pytorch-summary#29]
I got a syntax error just by importing

`from torchsummary import summary`

```Traceback (most recent call last):
 File "main.py", line 21, in <module>
    from torchsummary import summary
  File "/home/ivan/vox/torchsummary/__init__.py", line 1, in <module>
    from .torchsummary import summary
  File "/home/ivan/vox/torchsummary/torchsummary.py", line 9
    def summary(model, *input_size, batch_size=-1, device="cuda"):
                                             ^
SyntaxError: invalid syntax
```

Could you suggest where to look for the catch? Thanks

**Comment by ZSQflower** [comment]
I got the error too.

**Comment by sksq96** [comment]
Can you confirm, are you using Python 2?

Python 2 does not support the syntax of putting arguments after the `*` argument. I'll change it to be Python 2 compatible.

**Comment by ZSQflower** [comment]
In Python 2.7 env, I just change the corresponding code in  torchsummary.py as :
def summary(model, batch_size = -1, device = 'cuda', *input_size):
.....

and I use this API as (for example) : 
summary(net, -1, 'cuda', (3, 225, 225))   (for single input)
summary(net, -1, 'cuda', (3, 225, 225), (3, 225, 225))   (for multiple inputs)

and this works for me. Hope it could help.

**Comment by IvanEz** [comment]
> In Python 2.7 env, I just change the corresponding code in torchsummary.py as :
> def summary(model, batch_size = -1, device = 'cuda', *input_size):
> .....
> 
> and I use this API as (for example) :
> summary(net, -1, 'cuda', (3, 225, 225)) (for single input)
> summary(net, -1, 'cuda', (3, 225, 225), (3, 225, 225)) (for multiple inputs)
> 
> and this works for me. Hope it could help.

Yeap, that fixes the issue.

**Comment by sksq96** [comment]
Thank you for the suggestions.  The code is fixed to run correctly on Python2 now.
