### ISSUE TITLE
Can the function run when there are sequential containers in the model?

### ISSUE THREAD

**Issue by acnokegoo** [sksq96/pytorch-summary#3]
Hello, 

I have tried your summary function and found out that there would be errors while encountering sequential containers in the model. I am wondering if this function works on sequential containers or there are other problems in my model?

Thank you!

**Comment by sksq96** [comment]
- Well there is nothing inherently different about `nn.Sequential` that make the different that other models. I have tested on bunch of sequential models, it worked fine for me. 
- Perhaps you can share the model and error. We can have a look at the problem. 

Thanks!

**Comment by sksq96** [comment]
Yes, that was the issue. I have fixed it a few hours ago. Please upgrade the package or pull the latest code to test the changes.

I'm closing this issue, feel free to open it up if you face any further issues.
