### ISSUE TITLE
whats wrong with it

### ISSUE THREAD

**Issue by JoJo-ops** [sksq96/pytorch-summary#61]
File "main.py", line 301, in <module>
    summary(model.to(hyperparams['device']), input.size()[1:], device=hyperparams['device'])
  File "/home/anaconda3/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 44, in summary
    device = device.lower()

AttributeError: 'torch.device' object has no attribute 'lower'

**Comment by menghuu** [comment]
your `hyperparams['device']` should be `str` not `torch.device`, this https://github.com/sksq96/pytorch-summary/pull/34 may solve your problem or just change the type of your `hyperparams['device']` to `str`

**Comment by Naireen** [comment]
This was addressed with #107 , so I'll close this, reopen if you still run into any issues.

**Comment by hyeokhyen** [comment]
Still seeing this issue. I just installed with pip

**Comment by praneet195** [comment]
pip install still gives this error

**Comment by cjfghk5697** [comment]
I got same error when code is
```python
summary(model, (3, 224, 224), device=device.)
```
And replace the code from 'device=device' to 'device=device.type'. It is work well.
```python
summary(model, (3, 224, 224), device=device.type)
```
If modify the code as described above, it works fine.
