### ISSUE TITLE
a net with single module has no information printed out

### ISSUE THREAD

**Issue by harryhan618** [sksq96/pytorch-summary#9]
``` 
net = nn.Linear(2,3)
summary(net, (2,))
```

This will print no line since in function _register_hook_, ```module == model```.
I haven't figured out how to fix this.

**Comment by entalent** [comment]
I tried the same but got different error. Here's the output in python console:
`>>> a = torch.nn.Linear(5, 4)
>>> summary(a, (10, 5))
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\lib\site-packages\torchsummary\torchsummary.py", line 102, in summary
    total_params_size = abs(total_params.numpy() * 4. / (1024 ** 2.))
AttributeError: 'int' object has no attribute 'numpy'`

**Comment by Naireen** [comment]
This should now be resolved, so I'm closing the issue. Please reopen if you run into any additional errors.
