### ISSUE TITLE
Interface for providing string summary

### ISSUE THREAD

**Issue by greenmonn** [sksq96/pytorch-summary#99]
Hi, I recently found this pytorch-summary package, and using it really helps me to check the model in convenient way. Thanks!

By the way, I wonder you have any plan to support interface for **returning concatenated string of summary result**, instead of directly printing the summary to console.

I want to print the summary information to the log using the python `logging` feature, but the `summary` function just print the result to the console directly, so I cannot provide the summary result to my logger. If the interface is provided, I think this package would be more helpful.

**Comment by Naireen** [comment]
Closing this as #100 was merged
